const players = [
  { name: "Rohit Sharma", image: "https://documents.bcci.tv/resizedimageskirti/107_compress.png", age: "38", style: "Batter" },
  { name: "Virat Kohli", image: "https://documents.bcci.tv/resizedimageskirti/164_compress.png", age: "36", style: "Batter" },
  { name: "Jasprit Bumrah", image: "https://documents.bcci.tv/resizedimageskirti/1124_compress.png", age: "31", style: "Bowler" },
  { name: "Ravindra Jadeja", image: "https://documents.bcci.tv/resizedimageskirti/9_compress.png", age: "36", style: "All Rounder" },
  { name: "Mohammed Siraj", image: "https://documents.bcci.tv/resizedimageskirti/3840_compress.png", age: "Bowler", style: "Bowler" },
  { name: "Kl Rahul", image: "https://documents.bcci.tv/resizedimageskirti/1125_compress.png", age: "Wicket Keeper", style: "Wicket Keeper" },
  { name: "Shubman Gill", image: "https://documents.bcci.tv/resizedimageskirti/3761_compress.png", age: "Batter", style: "Batter" },
  { name: "Hardik Pandya", image: "https://documents.bcci.tv/resizedimageskirti/2740_compress.png", age: "All Rounder", style: "All Rounder" },
  { name: "Mohammad Shami", image: "https://documents.bcci.tv/resizedimageskirti/94_compress.png", age: "Bowler", style: "Bowler" },
  { name: "Rishabh Pant", image: "https://documents.bcci.tv/resizedimageskirti/2972_compress.png", age: "Wicket Keeper", style: "Wicket Keeper" },
  { name: "Suryakumar Yadav", image: "https://documents.bcci.tv/resizedimageskirti/1212_compress.png", age: "34", style: "Batter" },
  { name: "Kuldeep Yadav", image: "https://documents.bcci.tv/resizedimageskirti/261_compress.png", age: "30", style: "Bowler" },
  { name: "Axar Patel", image: "https://documents.bcci.tv/resizedimageskirti/1113_compress.png", age: "31", style: "Bowler" },
  { name: "Yashasvi Jaiswal", image: "https://documents.bcci.tv/resizedimageskirti/11086_compress.png", age: "23", style: "Batter" },
  { name: "Shreyas Iyer", image: "https://documents.bcci.tv/resizedimageskirti/1563_compress.png", age: "30", style: "Batter" },
  { name: "Rinku Singh", image: "https://documents.bcci.tv/resizedimageskirti/11087_compress.png", age: "27", style: "Batter" },
  { name: "Tilak Varma", image: "https://documents.bcci.tv/resizedimageskirti/11088_compress.png", age: "22", style: "Batter" },
  { name: "Ruturaj Gaikwad", image: "https://documents.bcci.tv/resizedimageskirti/11095_compress.png", age: "28", style: "Batter" },
  { name: "Shivam Dube", image: "https://documents.bcci.tv/resizedimageskirti/11089_compress.png", age: "32", style: "All Rounder" },
  { name: "Ravi Bishnoi", image: "https://documents.bcci.tv/resizedimageskirti/11084_compress.png", age: "24", style: "Bowler" },
  { name: "Washington Sundar", image: "https://documents.bcci.tv/resizedimageskirti/2973_compress.png", age: "25", style: "All Rounder" },
  { name: "Mukesh Kumar", image: "https://documents.bcci.tv/resizedimageskirti/11091_compress.png", age: "31", style: "Bowler" },
  { name: "Sanju Samson", image: "https://documents.bcci.tv/resizedimageskirti/37_compress.png", age: "30", style: "Wicket Keeper" },
  { name: "Arshdeep Singh", image: "https://documents.bcci.tv/resizedimageskirti/65_compress.png", age: "26", style: "Bowler" },
  { name: "Prasidh Krishna", image: "https://documents.bcci.tv/resizedimageskirti/11092_compress.png", age: "29", style: "Bowler" },
  { name: "Rajat Patidar", image: "https://documents.bcci.tv/resizedimageskirti/11093_compress.png", age: "32", style: "Batter" },
  { name: "Dhruv Jurel", image: "https://documents.bcci.tv/resizedimageskirti/11097_compress.png", age: "24", style: "Wicket Keeper" },
  { name: "Sarfaraz Khan", image: "https://documents.bcci.tv/resizedimageskirti/11096_compress.png", age: "27", style: "Batter" },
  { name: "Nitish Kumar", image: "https://documents.bcci.tv/resizedimageskirti/11106_compress.png", age: "22", style: "All Rounder" },
  { name: "Ishan Kishan", image: "https://documents.bcci.tv/resizedimageskirti/31_compress.png", age: "27", style: "Wicket Keeper" },
  { name: "Abhishek Sharma", image: "https://documents.bcci.tv/resizedimageskirti/11099_compress.png", age: "24", style: "Batter" },
  { name: "Akash Deep", image: "https://documents.bcci.tv/resizedimageskirti/11107_compress.png", age: "28", style: "Bowler" },
  { name: "Varun Chakaravarthy", image: "https://documents.bcci.tv/resizedimageskirti/11100_compress.png", age: "33", style: "Bowler" },
  { name: "Harshit Rana", image: "https://documents.bcci.tv/resizedimageskirti/11108_compress.png", age: "23", style: "Bowler" },
];

export default players;
